- name: Assign SD-WAN templates
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
       - -2 # already exists
    params:
      - url: "/pm/wanprof/adom/{{ item.fmgr_target_adom }}/{{ item.templates[0].sdwan }}/scope member"
        data:
          - name: '{{ item.fgt_name }}'
            vdom: "{{ item.fgt_vdom }}"
  loop: "{{ ztp_fortigates }}"
  when: item.templates | length == 1