---
- name: Assign fortiswitch template
  fortinet.fortimanager.fmgr_generic:
    method: update
    params:
      - url: "/pm/config/adom/{{ item.0.fmgr_target_adom }}/obj/fsp/managed-switch/{{ item.1.fortiswitch_serial_number }}"
        data:
          template: '{{ item.1.fortiswitch_template }}'
        'scope member':
          - name: '{{ item.0.fgt_name }}'
            vdom: '{{ item.0.fgt_vdom }}'
  loop: "{{ ztp_fortigates | subelements('fortiswitches')}}"
  when: item.1.fortiswitch_template
