- name: Assign Fortigates to ADOM Policy Packages
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/pkg/adom/{{ item.0.fmgr_target_adom }}/{{ item.1.policy_package }}/scope member'
        data:
          name: '{{ item.0.fgt_name }}'
          vdom: "{{ item.0.fgt_vdom }}"
  loop: "{{ ztp_fortigates | subelements('policy_packages')}}"



