- name: Assign provisioning templates
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: "/pm/devprof/adom/{{ item.fmgr_target_adom }}/{{ item.templates[0].provisioning }}/scope member"
        data:
          name: '{{ item.fgt_name }}'
          vdom: "{{ item.fgt_vdom }}"
  loop: "{{ ztp_fortigates }}"
  when: item.templates | length == 1 and item.templates[0].provisioning
