---

#- debug: var=ztp_fortigates

- name: Find the rendered fortigate definition files
  find:
    paths: "{{role_path}}/files/tmp/fortigates/"
    patterns: "*.yml,*.yaml"
  register: rendered_fgt_files

#- debug: var=rendered_fgt_files
- set_fact:
    tmp_fgt_paths: []
- set_fact:
    tmp_fgt_paths: "{{ tmp_fgt_paths + [ item.path ] }}"
  loop: "{{ rendered_fgt_files.files|flatten(levels=1) }}"

- debug: var=tmp_fgt_paths

- name: Validate Fortigates on Ansible ZTP Role Data Model
  shell: "python3 {{role_path}}/files/python/ansible_ztp_role_data_model/validate_rendered_fortigates.py -d '{{ tmp_fgt_paths | to_json }}'"
  register: validation_results


- name: Validation Results
  debug: var=validation_results.stdout

