- name: Add cli templates
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ default_fmgr_target_adom }}/obj/cli/template'
        data:
          name: '{{ item.name }}'
          script: '{{ item.script }}'
          description: '{{ default_fmgr_object_description_string }}'


  with_items: '{{ cli_templates }}'

