- fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ default_fmgr_target_adom }}/obj/cli/template-group'
        data:
          name: '{{ item }}'
          description: '{{ default_fmgr_object_description_string }}'
  loop: "{{ ztp_cli_template_group_names }}"
