---

- set_fact:
    policy_security_profiles: "{{ lookup('template', 'policy_packages/get_security_profiles.j2') }}"

#- debug: var=policy_security_profiles


- name: Add Global File Filter Security Profiles
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/global/obj/file-filter/profile'
        data:
          name: "{{ item.1 }}"
          comment: "{{ default_fmgr_object_description_string }}"
  loop: "{{ policy_security_profiles | subelements('file_filter')}}"
  when: item.0.adom == 'Global' and item.1 != 'default'