- name: Get cli templates
  fortinet.fortimanager.fmgr_generic:
    method: get
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ default_fmgr_target_adom }}/obj/cli/template'
#        data:
#          name: '{{ item.name }}'
#          script: '{{ item.script }}'
  register: fmgr_cli_templates
#  with_items: '{{ cli_templates }}'

