---
- set_fact:
    address_groups: []

- set_fact:
    address_groups: "{{ address_groups +  item.address_groups  }}"
  loop: "{{ ztp_fortigates }}"

#- debug: var=address_groups

- set_fact:
    address_objects: []

- set_fact:
    address_objects: "{{ address_objects + [{'adom': item.adom, 'subnets': item.subnets }] }}"
  loop: "{{ address_groups  }}"

#- debug: var=address_objects

- set_fact:
    flatten_address_objects: "{{ address_objects | flatten(levels=1) | unique }}"

#- debug: var=flatten_address_objects
#- debug: var=address_groups

- set_fact:
    flattened_address_groups: "{{ address_groups | json_query('[].{name: name, subnets: subnets, adom: adom}') | unique }}"

#- debug: var=flattened_address_groups

- name: Add address objects for groups
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ item.0.adom }}/obj/firewall/address'
        data:
          name: "{{ item.1 }}"
          comment: "{{ default_fmgr_object_description_string }}"
          subnet: "{{ item.1 }}"
          type: "ipmask"
          associated-interface: "any"
  loop: "{{ flatten_address_objects | subelements('subnets') }}"

- name: Add address Groups
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ item.adom }}/obj/firewall/addrgrp'
        data:
          name: "{{ item.name }}"
          comment: "{{ default_fmgr_object_description_string }}"
          member: "{{ item.subnets }}"
  loop: "{{ flattened_address_groups }}"
