---
- set_fact:
    vlan_mappings: []

- set_fact:
    vlan_mappings: "{{ vlan_mappings + [{
    'fgt_name': item.0.fgt_name,
    'fmgr_target_adom': item.0.fmgr_target_adom,
    'fmgr_object_description_string': item.0.fmgr_object_description_string,
    'fgt_vdom': item.0.fgt_vdom} | combine(item.1)

    ] }}"
  loop: "{{ ztp_fortigates|subelements('fgt_lan_vlan_map') }}"

#- debug: var=vlan_mappings

- name: Add dynamic address object
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ item.fmgr_target_adom }}/obj/firewall/address'
        data:
          name: "{{ item.network_alias }}"
          comment: "{{ item.fmgr_object_description_string }}"
          subnet: "255.255.255.255/255.255.255.255"
          type: "ipmask"
          associated-interface: "any"
  loop: "{{ vlan_mappings }}"


- name: Add address object dynamic mappings
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ item.fmgr_target_adom }}/obj/firewall/address/{{ item.network_alias }}/dynamic_mapping'
        data:
          - _scope:
            - name: "{{ item.fgt_name }}"
              vdom: "{{ item.fgt_vdom }}"
            subnet: "{{ item.ipv4_subnet }}"
  loop: "{{ vlan_mappings }}"

