- name: Add device metafields
  fortinet.fortimanager.fmgr_generic:
    method: add
    params:
      - url: /dvmdb/_meta_fields/device
        data:
          name: '{{ item }}'
          importance: optional
          length: 50
          status: 1
    rc_succeeded:
      - 0
      - -8      

  loop: '{{ device_metafields }}'
