---
- set_fact:
    normalized_interfaces: "{{ lookup('template', 'interfaces/normalized_interfaces.j2')  }}"

- debug: var=normalized_interfaces


- set_fact:
    flattened_normalized_interfaces: "{{ normalized_interfaces |
    json_query('[].{
    normalized_interface: normalized_interface,
    fmgr_target_adom: fmgr_target_adom,
    fmgr_object_description_string: fmgr_object_description_string
    }') | unique }}"

#- debug: var=flattened_normalized_interfaces


- name: Add normalized interfaces
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ item.fmgr_target_adom }}/obj/dynamic/interface'
        data:
          name: '{{ item.normalized_interface }}'
          description: '{{ item.fmgr_object_description_string }}'
  loop: "{{ flattened_normalized_interfaces }}"


- name: Add normalized interface mappings
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ item.fmgr_target_adom }}/obj/dynamic/interface/{{ item.normalized_interface }}/dynamic_mapping'
        data:
          - _scope:
              - name: '{{ item.fgt_name }}'
                vdom: '{{ item.fgt_vdom }}'
            local-intf: '{{ item.local_port }}'
  loop: "{{ normalized_interfaces }}"
