- name: Add ADOM policy packages
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/pkg/adom/{{ item.0.fmgr_target_adom }}/'
        data:
          name: '{{ item.1.policy_package }}'
          type: pkg
  loop: "{{ ztp_fortigates | subelements('policy_packages')}}"
