---
- set_fact:
    sdwan_zones: "{{ lookup('template', 'interfaces/sdwan_normalized_interfaces.j2')  }}"

- debug: var=sdwan_zones


- name: Add normalized interfaces
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ item.fmgr_target_adom }}/obj/dynamic/interface'
        data:
          name: '{{ item.normalized_interface }}'
          description: '{{ item.fmgr_object_description_string }}'
  loop: "{{ sdwan_zones }}"


- name: Add normalized interface mappings
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/config/adom/{{ item.fmgr_target_adom }}/obj/dynamic/interface/{{ item.normalized_interface }}/dynamic_mapping'
        data:
          - _scope:
              - name: '{{ item.fgt_name }}'
                vdom: '{{ item.fgt_vdom }}'
            local-intf: '{{ item.local_port }}'
  loop: "{{ sdwan_zones }}"
