- name: Add system templates
  fortinet.fortimanager.fmgr_generic:
    method: add
    rc_succeeded:
      - 0
      - -2 # already exists
    params:
      - url: '/pm/devprof/adom/{{ item.fmgr_target_adom }}'
        data:
          name: '{{ item.fgt_system_template }}'
          description: '{{ item.fmgr_object_description_string }}'
          type: devprof
          enabled options:
            - admin
  loop: "{{ ztp_fortigates }}"
