- hosts: localhost
  collections:
    - fortinet.fortimanager
  tasks:

    - include_role:
        name: ../roles/fortigate.ztp
        tasks_from: templates/import_spreadsheet
      vars:
        spreadsheet_path: "{{ role_path }}/files/spreadsheets/Ansible_ZTP_Local_Simple_Topology.xlsx"


