---
- hosts: localhost
  gather_facts: no
  collections:
    - fortinet.fortimanager
  tasks:

    - include_role:
        name: ../roles/fortigate.ztp
        tasks_from: templates/read_rendered_fortigates


- hosts: fortimanager
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortimanager
  tasks:

    - include_role:
        name: ../roles/fortigate.ztp
        tasks_from: assign/system_templates
      vars:
        ztp_fortigates: "{{ hostvars['localhost']['ztp_fortigates'] }}"