---
- hosts: localhost
  collections:
    - fortinet.fortimanager
  tasks:

    - include_role:
        name: ../roles/fortigate.ztp
        tasks_from: templates/read_rendered_fortigates


- hosts: fortimanager
  connection: httpapi
  collections:
    - fortinet.fortimanager
  tasks:

    - include_role:
        name: ../roles/fortigate.ztp
        tasks_from: install/policy_package
      vars:
        ztp_fortigates: "{{ hostvars['localhost']['ztp_fortigates'] }}"