---
- hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "RESET_ROLE"
      prompt: "ARE YOU SURE YOU WANT TO DELETE ALL GENERATED CONTENT IN THIS ROLE? (yes/no)"
      private: no

  tasks:

    - include_role:
        name: ../roles/fortigate.ztp
        tasks_from: debug/reset_role_to_default
      when:
        - RESET_ROLE == "yes"
